name: the_boys
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_pattern: ^3.0.1
  connectivity_plus: ^4.0.2
  rive: 0.9.1
  vibration: ^1.8.1
  go_router: ^13.0.1
  random_avatar: ^0.0.8
  flutter_animated_button: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/rive/icons.riv
    - assets/rive/the_boys_button.riv
